import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Link } from 'react-router-dom';
import { Reveal, Stagger, StaggerItem } from './Motion.jsx';
import ScanOverlay from './ScanOverlay.jsx';

function useSpeech() {
  const [listening, setListening] = useState(false);

  const speak = (text) => {
    if (!('speechSynthesis' in window)) return;
    window.speechSynthesis.cancel();
    const utterance = new SpeechSynthesisUtterance(text);
    utterance.rate = 0.95;
    utterance.onend = () => setListening(false);
    utterance.onerror = () => setListening(false);
    setListening(true);
    window.speechSynthesis.speak(utterance);
  };

  const stop = () => {
    window.speechSynthesis?.cancel();
    setListening(false);
  };

  return { speak, stop, listening };
}

function computeHealthScore(data) {
  const critical = data.critical_values || [];
  let score = 100;
  critical.forEach((c) => {
    score -= c.severity === 'critical' ? 26 : 14;
  });
  return Math.max(15, Math.min(100, score));
}

function scoreMeta(score) {
  if (score >= 90) return { label: 'Looking good', icon: '✅', color: 'var(--success)' };
  if (score >= 70) return { label: 'Mostly normal', icon: '👍', color: '#22d3ee' };
  if (score >= 40) return { label: 'Follow-up advised', icon: '⚠️', color: 'var(--warning)' };
  return { label: 'Needs urgent review', icon: '🚨', color: 'var(--critical)' };
}

function healthLevel(score) {
  if (score >= 90) return ['var(--success)', 'Excellent'];
  if (score >= 70) return ['#22d3ee', 'Good'];
  if (score >= 40) return ['var(--warning)', 'Moderate'];
  return ['var(--critical)', 'Concern'];
}

export default function ResultView({ data }) {
  const [showExtracted, setShowExtracted] = useState(false);
  const speech = useSpeech();

  if (!data) return null;

  const score = computeHealthScore(data);
  const meta = scoreMeta(score);
  const [barColor, levelLabel] = healthLevel(score);
  const alertCount = data.critical_values?.length || 0;
  const findingsCount = data.key_findings?.length || 0;
  const medCount = data.medications?.length || 0;
  const questionCount = data.questions?.length || 0;

  const downloadTxt = () => {
    const content = [
      'MEDISCAN AI - MEDICAL REPORT ANALYSIS',
      `Date: ${new Date().toLocaleDateString()}`,
      '',
      '=== SUMMARY ===',
      data.summary,
      '',
      alertCount ? '=== CRITICAL VALUES ===\n' + data.critical_values.map((a) => `- ${a.title}: ${a.message}`).join('\n') : null,
      '',
      '=== QUESTIONS FOR YOUR DOCTOR ===',
      ...(data.questions?.map((q, i) => `${i + 1}. ${q}`) || []),
    ]
      .filter(Boolean)
      .join('\n');

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `mediscan-report-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadPdf = async () => {
    const { jsPDF } = await import('jspdf');
    const doc = new jsPDF();
    doc.setFillColor(109, 94, 242);
    doc.rect(0, 0, 210, 34, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.text('MediScan AI', 14, 16);
    doc.setFontSize(11);
    doc.text(`Medical Report Analysis - ${new Date().toLocaleDateString()}`, 14, 25);

    let y = 46;
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text('Plain Language Summary', 14, y);
    y += 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10.5);
    const summaryLines = doc.splitTextToSize(data.summary, 182);
    if (y + summaryLines.length * 6 > 285) {
      doc.addPage();
      y = 20;
    }
    doc.text(summaryLines, 14, y);
    y += summaryLines.length * 6 + 12;

    if (alertCount) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(13);
      doc.setTextColor(220, 38, 38);
      doc.text('Critical Values', 14, y);
      y += 8;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10.5);
      data.critical_values.forEach((a) => {
        if (y > 280) {
          doc.addPage();
          y = 20;
        }
        doc.setTextColor(30, 30, 30);
        doc.text(`${a.title}: ${a.message}`, 16, y);
        y += 6;
      });
      y += 10;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(30, 30, 30);
    doc.text('Questions to Ask Your Doctor', 14, y);
    y += 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10.5);
    data.questions?.forEach((q, i) => {
      if (y > 285) {
        doc.addPage();
        y = 20;
      }
      doc.text(`${i + 1}. ${q}`, 16, y);
      y += 6;
    });

    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by MediScan AI. Always consult a healthcare professional.', 14, 290);

    doc.save(`mediscan-report-${Date.now()}.pdf`);
  };

  const alertIcon = (sev) => (sev === 'critical' ? '🚨' : '⚠️');

  return (
    <div className="results-section" id="resultsSection">
      {/* Header */}
      <Reveal>
        <div className="results-header">
          <div>
            <div className="results-kicker">✨ Analysis complete</div>
            <h2>Your results</h2>
            <div style={{ color: 'var(--text-light)', fontSize: '0.9rem', marginTop: '0.3rem' }}>
              {data.category || 'Report'} · {data.analyzed_at ? new Date(data.analyzed_at).toLocaleString() : new Date().toLocaleString()}
            </div>
          </div>
          <div className="results-actions">
            <button className="btn btn-ghost btn-sm" onClick={() => speech.speak(data.summary)}>
              {speech.listening ? '🔊 Playing…' : '🔊 Listen'}
            </button>
            {speech.listening && (
              <button className="btn btn-outline btn-sm" onClick={speech.stop}>⏹ Stop</button>
            )}
            <button className="btn btn-ghost btn-sm" onClick={downloadTxt}>📥 TXT</button>
            <button className="btn btn-ghost btn-sm" onClick={downloadPdf}>📄 PDF</button>
          </div>
        </div>
      </Reveal>

      {/* Smart health score + stat chips */}
      <Reveal delay={0.05}>
        <div className="score-strip">
          <motion.div
            className="score-gauge"
            initial={{ opacity: 0, scale: 0.85 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 0.15, type: 'spring', stiffness: 220, damping: 18 }}
            style={{ '--score': `${score * 3.6}deg`, '--score-color': barColor }}
          >
            <div className="score-ring">
              <div className="score-center">
                <strong>{score}</strong>
                <span>Health score</span>
              </div>
            </div>
            <div className="score-label" style={{ color: barColor }}>
              <span>{meta.icon}</span> {meta.label} · {levelLabel}
            </div>
          </motion.div>

          <div className="score-stats">
            {[
              { value: alertCount, label: 'Critical alerts', icon: '🚨' },
              { value: findingsCount, label: 'Key findings', icon: '🔍' },
              { value: medCount, label: 'Medications', icon: '💊' },
              { value: questionCount, label: 'Questions', icon: '❓' },
            ].map((s) => (
              <div className="stat-chip" key={s.label}>
                <span className="stat-chip-icon">{s.icon}</span>
                <strong>{s.value}</strong>
                <span>{s.label}</span>
              </div>
            ))}
          </div>
        </div>
      </Reveal>

      {/* Critical alerts */}
      <AnimatePresence>
        {alertCount > 0 ? (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
            {data.critical_values.map((a, i) => (
              <motion.div
                key={a.title}
                className={`alert-card ${a.severity || 'warning'}`}
                initial={{ opacity: 0, x: -24 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.15 + i * 0.15 }}
              >
                <span className="alert-icon">{alertIcon(a.severity)}</span>
                <div>
                  <strong>{a.title}</strong>
                  <p>{a.message}</p>
                </div>
              </motion.div>
            ))}
          </motion.div>
        ) : (
          <motion.div className="alert-card success" initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }}>
            <span className="alert-icon">✅</span>
            <div>
              <strong>No critical values detected</strong>
              <p>Nothing in this report was flagged as dangerous, but always confirm with your doctor.</p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Scan fault-marking */}
      {data.scan_image && (
        <Reveal delay={0.08}>
          <div className="card result-block">
            <div className="result-block-header">
              <div className="block-icon">🎯</div>
              <h3>Scan Analysis — Marked Areas</h3>
              {data.detect_engine && (
                <span className={`engine-badge ${data.detect_engine}`}>
                  {data.detect_engine === 'yolo' ? '🤖 YOLO' : data.detect_engine === 'opencv' ? '🧪 OpenCV' : '🧠 AI Vision'}
                </span>
              )}
            </div>
            <ScanOverlay image={data.scan_image} findings={data.scan_findings || []} note={data.scan_note} />
          </div>
        </Reveal>
      )}

      {/* Summary */}
      <Reveal delay={0.1}>
        <div className="card result-block">
          <div className="result-block-header">
            <div className="block-icon">📋</div>
            <h3>Plain Language Summary</h3>
          </div>
          <p className="summary-text">{data.summary}</p>
        </div>
      </Reveal>

      {/* Key findings */}
      {findingsCount > 0 && (
        <Reveal delay={0.15}>
          <div className="card result-block">
            <div className="result-block-header">
              <div className="block-icon">🔍</div>
              <h3>Key Findings</h3>
            </div>
            <ul className="findings-list">
              {data.key_findings.map((f, i) => (
                <motion.li key={i} initial={{ opacity: 0, y: 10 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.08 }}>
                  {f}
                </motion.li>
              ))}
            </ul>
          </div>
        </Reveal>
      )}

      {/* Medications */}
      {medCount > 0 && (
        <Reveal delay={0.15}>
          <div className="card result-block">
            <div className="result-block-header">
              <div className="block-icon">💊</div>
              <h3>Medications Detected</h3>
            </div>
            <div className="med-list">
              {data.medications.map((m, i) => (
                <div className="med-item" key={i}>
                  <strong>{m.name}</strong>
                  <span>{m.dosage && `${m.dosage} `}{m.frequency}</span>
                </div>
              ))}
            </div>
          </div>
        </Reveal>
      )}

      {/* Questions */}
      <Reveal delay={0.2}>
        <div className="card result-block">
          <div className="result-block-header">
            <div className="block-icon">❓</div>
            <h3>Questions to Ask Your Doctor</h3>
          </div>
          <Stagger className="questions-list">
            {data.questions?.map((q) => (
              <StaggerItem key={q}>
                <li>{q}</li>
              </StaggerItem>
            ))}
          </Stagger>
        </div>
      </Reveal>

      {/* Extracted text */}
      <Reveal delay={0.25}>
        <button className="extracted-toggle" onClick={() => setShowExtracted((v) => !v)}>
          {showExtracted ? 'Hide Extracted Text ▲' : 'Show Extracted Text ▼'}
        </button>
        <AnimatePresence>
          {showExtracted && (
            <motion.pre className="extracted-text" initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, minHeight: 80 }} exit={{ opacity: 0, height: 0 }}>
              {data.extracted_text}
            </motion.pre>
          )}
        </AnimatePresence>
      </Reveal>

      <Reveal delay={0.3}>
        <div className="analyze-actions" style={{ marginTop: '2rem' }}>
          <Link to="/chat" className="btn btn-ghost">💬 Ask about this report</Link>
        </div>
      </Reveal>
    </div>
  );
}
